# parse_data.ipynb

This notebook parses the data files used for the FP-2 assignment. 

<br>
<br>

First let's read the attached data file:

In [15]:
import pandas as pd

df0 = pd.read_csv('SeoulBikeData.csv')

df0.describe()

,Rented Bike Count,Hour,Temperature(?C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(?C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holidays,Functioning Day
count,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000
mean,704.602055,11.500000,12.882922,58.226256,1.724909,1436.825799,4.073813,0.569111,0.148687,0.075068,2.504110,0.049315,0.966324
std,644.997468,6.922582,11.944825,20.362413,1.036300,608.298712,13.060369,0.868746,1.128193,0.436746,1.114408,0.216537,0.180404
min,0.000000,0.000000,-17.800000,0.000000,0.000000,27.000000,-30.600000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,191.000000,5.750000,3.500000,42.000000,0.900000,940.000000,-4.700000,0.000000,0.000000,0.000000,2.000000,0.000000,1.000000
50%,504.500000,11.500000,13.700000,57.000000,1.500000,1698.000000,5.100000,0.010000,0.000000,0.000000,3.000000,0.000000,1.000000
75%,1065.250000,17.250000,22.500000,74.000000,2.300000,2000.000000,14.800000,0.930000,0.000000,0.000000,3.000000,0.000000,1.000000
max,3556.000000,23.000000,39.400000,98.000000,7.400000,2000.000000,27.200000,3.520000,35.000000,8.800000,4.000000,1.000000,1.000000

<br>
<br>
The dependent and independent variables variables (DVs and IVs) that we are interested in are:

**DVs**:
- Rentend Bike Count (the rented bike count in an hour, "rented bike count" in the csv)

**IVs**:
- Date ("date" column in csv)
- Hour ("hour" column in csv)
- Temperature ("temperature °C" in csv)
- Humidity ("humidity %" in csv)
- Windspeed ("wind speed m/s" in csv)
- Visibility ("visibility (10m)" in csv)
- Dew point temperature ("dew point temperature (C)" in csv)
- Solar radiation ("solar radiation MJ/m2" in csv)
- Rainfall ("Rainfall mm" in csv)
- Snowfall ("Snowfall cm" in csv)
- Seasons ("Seasons" in csv)
- Whether it is a holiday ("Holiday" in csv)
- Whether it is a functional day ("Functioning Day" in csv)

**IMPORTANT NOTE**
I have changed the following in the csv: 
Seasons is now a integer between 1 and 4, with a mapping of 1 -> Winter, 2 -> Spring, 3 -> Summer, 4 -> Autumn
Holidays is now a boolean, with a mapping of 1 -> Holiday, 2 -> Not Holiday
Functional day is now a boolean, with a mapping of 1 -> Functional day, 2 -> Not functional day
"Preferably I would have changed the Date into month and day if possible but I don't know how much of the original dataset I should modify"
And some stuff was weird with the temperature symbol where it was "ｰ" in the original csv so I (excel automatically) changed it to ? 



<br>
<br>

Let's extract the relevant columns:

In [16]:

df = df0[  ['Rented Bike Count','Hour','Temperature(?C)','Humidity(%)','Wind speed (m/s)','Visibility (10m)','Dew point temperature(?C)','Solar Radiation (MJ/m2)','Rainfall(mm)','Snowfall (cm)',
            'Seasons','Holidays','Functioning Day']  ]

df.describe()

,Rented Bike Count,Hour,Temperature(?C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(?C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holidays,Functioning Day
count,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000
mean,704.602055,11.500000,12.882922,58.226256,1.724909,1436.825799,4.073813,0.569111,0.148687,0.075068,2.504110,0.049315,0.966324
std,644.997468,6.922582,11.944825,20.362413,1.036300,608.298712,13.060369,0.868746,1.128193,0.436746,1.114408,0.216537,0.180404
min,0.000000,0.000000,-17.800000,0.000000,0.000000,27.000000,-30.600000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,191.000000,5.750000,3.500000,42.000000,0.900000,940.000000,-4.700000,0.000000,0.000000,0.000000,2.000000,0.000000,1.000000
50%,504.500000,11.500000,13.700000,57.000000,1.500000,1698.000000,5.100000,0.010000,0.000000,0.000000,3.000000,0.000000,1.000000
75%,1065.250000,17.250000,22.500000,74.000000,2.300000,2000.000000,14.800000,0.930000,0.000000,0.000000,3.000000,0.000000,1.000000
max,3556.000000,23.000000,39.400000,98.000000,7.400000,2000.000000,27.200000,3.520000,35.000000,8.800000,4.000000,1.000000,1.000000

<br>
<br>

Next let's use the `rename` function to give the columns simpler variable names:

In [17]:
df = df.rename( columns={'Rented Bike Count':'Bike_Count', 'Temperature(?C)':'Temperature','Humidity(%)':'Humidity','Wind speed (m/s)':'Wind Speed','Visibility (10m)':'Visibility','Dew point temperature(?C)':'Dew Point Temperature','Solar Radiation (MJ/m2)':'Solar Radiation','Rainfall(mm)':'Rainfall','Snowfall (cm)':'Snowfall'} )

df.describe()

,Bike_Count,Hour,Temperature,Humidity,Wind Speed,Visibility,Dew Point Temperature,Solar Radiation,Rainfall,Snowfall,Seasons,Holidays,Functioning Day
count,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000
mean,704.602055,11.500000,12.882922,58.226256,1.724909,1436.825799,4.073813,0.569111,0.148687,0.075068,2.504110,0.049315,0.966324
std,644.997468,6.922582,11.944825,20.362413,1.036300,608.298712,13.060369,0.868746,1.128193,0.436746,1.114408,0.216537,0.180404
min,0.000000,0.000000,-17.800000,0.000000,0.000000,27.000000,-30.600000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,191.000000,5.750000,3.500000,42.000000,0.900000,940.000000,-4.700000,0.000000,0.000000,0.000000,2.000000,0.000000,1.000000
50%,504.500000,11.500000,13.700000,57.000000,1.500000,1698.000000,5.100000,0.010000,0.000000,0.000000,3.000000,0.000000,1.000000
75%,1065.250000,17.250000,22.500000,74.000000,2.300000,2000.000000,14.800000,0.930000,0.000000,0.000000,3.000000,0.000000,1.000000
max,3556.000000,23.000000,39.400000,98.000000,7.400000,2000.000000,27.200000,3.520000,35.000000,8.800000,4.000000,1.000000,1.000000